package com.viewfunction.activityEngine.extension;

public enum ActivityEventType {
	ACTIVITYSTEP_ASSIGNED,
	ACTIVITYSTEP_CREATED,
	ACTIVITYSTEP_COMPLETED,
	BUSINESSACTIVITY_COMPLETED,
	BUSINESSACTIVITY_CANCELLED,
	ACTIVITYSTEPMONITOR_SUCCESS,
	ACTIVITYSTEPMONITOR_FAILURE,
	ACTIVITYSTEPMONITOR_RETRY_DECREMENTED,
	ACTIVITYSTEPMONITOR_CANCELED,
	ACTIVITYEVENT_UNKNOWN
}
